INSERT INTO CORES VALUES(1,'BRANCO');
INSERT INTO CORES VALUES(2,'PRETO');
INSERT INTO CORES VALUES(3,'VERMELHO');
INSERT INTO CORES VALUES(4,'AZUL');
INSERT INTO CORES VALUES(5,'AMARELO');
INSERT INTO CORES VALUES(6,'MARRON');
INSERT INTO CORES VALUES(7,'BRANCO PÉROLA');
INSERT INTO CORES VALUES(8,'AZUL MARINE');
INSERT INTO CORES VALUES(9,'CINZA CHUMBO');
INSERT INTO CORES VALUES(10,'PRATA');
INSERT INTO CORES VALUES(11,'VERMELHO VERSALHES');
INSERT INTO CORES VALUES(12,'PRETO CADILLAC');
INSERT INTO CORES VALUES(13,'VERMELHO FERRARI');
INSERT INTO CORES VALUES(14,'AZUL PÉROLA');
INSERT INTO CORES VALUES(15,'BEGE');
INSERT INTO CORES VALUES(16,'VERDE MUSGO');
INSERT INTO CORES VALUES(17,'VERDE');

