delete from modelo;
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1,25,'INTEGRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2,25,'LEGEND');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3,25,'NSX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4,27,'MARRUA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5,28,'145');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(6,28,'147');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(7,28,'155');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(8,28,'156');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(9,28,'164');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(10,28,'166');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(11,28,'2300');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(12,28,'SPIDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(13,156,'HUMMER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(14,16,'AM-825');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(15,16,'HI-TOPIC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(16,16,'ROCSTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(17,16,'TOPIC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(18,16,'TOWNER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(19,32,'100');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(20,32,'80');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(21,32,'A1');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(22,32,'A3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(23,32,'A4 SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(24,32,'A5 COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(25,32,'A6 SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(26,32,'A7');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(27,32,'A8');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(30,32,'Q3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(31,32,'Q5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(32,32,'Q7');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(33,32,'R8');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(34,32,'RS3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(35,32,'RS4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(36,32,'RS5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(37,32,'RS6');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(38,32,'S3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(39,32,'S4 SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(40,32,'S6 SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(41,32,'S8');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(42,32,'TT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(43,32,'TTS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(86,157,'BUGGY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(87,155,'DEVILLE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(88,155,'ELDORADO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(89,155,'SEVILLE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(90,42,'JAVALI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(92,6,'MINI STAR FAMILY    ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(93,6,'MINI STAR UTILITY    ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(95,47,'CIELO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(96,47,'FACE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(97,47,'QQ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(98,47,'S-18');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(99,47,'TIGGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(100,19,'300C');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(101,19,'CARAVAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(102,19,'CIRRUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(103,19,'GRAN CARAVAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(104,19,'LE BARON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(105,19,'NEON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(106,19,'PT CRUISER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(107,19,'SEBRING');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(108,19,'STRATUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(109,19,'TOWN E COUNTRY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(110,19,'VISION');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(111,5,'AIRCROSS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(112,5,'AX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(113,5,'BERLINGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(114,5,'BX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(115,5,'C3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(116,5,'C4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(117,5,'C5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(118,5,'C6');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(119,5,'C8');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(120,5,'DS3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(121,5,'EVASION');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(122,5,'JUMPER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(123,5,'XANTIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(124,5,'XM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(125,5,'XSARA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(126,5,'ZX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(127,50,'CL-244');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(128,50,'CL-330');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(129,51,'ESPERO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(130,51,'LANOS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(131,51,'LEGANZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(132,51,'NUBIRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(133,51,'PRINCE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(134,51,'RACER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(135,51,'SUPER SALON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(136,51,'TICO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(137,52,'APPLAUSE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(138,52,'CHARADE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(139,52,'CUORE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(140,52,'FEROZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(141,52,'GRAN MOVE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(142,52,'MOVE VAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(143,52,'TERIOS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(144,18,'AVENGER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(145,18,'DAKOTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(146,18,'JOURNEY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(147,18,'RAM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(148,18,'STEALTH');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(151,61,'M-100');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(152,61,'PLUTUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(153,61,'START');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(155,61,'ULC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(158,63,'ENGESA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(159,64,'CAMPER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(160,64,'MASTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(161,10,'348');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(162,10,'355');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(163,10,'360');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(164,10,'456');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(165,10,'550');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(166,10,'575M');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(167,10,'612');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(168,10,'CALIFORNIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(169,10,'F430');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(170,10,'F599');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(171,3,'147');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(174,3,'500');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(175,3,'BRAVA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(176,3,'BRAVO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(178,3,'COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(179,3,'DOBLO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(180,3,'DUCATO CARGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(181,3,'DUNA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(182,3,'ELBA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(183,3,'FIORINO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(184,3,'FREEMONT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(185,3,'GRAND SIENA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(186,3,'IDEA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(187,3,'LINEA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(188,3,'MAREA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(189,3,'OGGI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(190,3,'PALIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(191,3,'PANORAMA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(192,3,'PREMIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(193,3,'PUNTO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(194,3,'SIENA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(195,3,'STILO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(196,3,'STRADA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(197,3,'TEMPRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(198,3,'TIPO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(199,3,'UNO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(201,13,'AEROSTAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(202,13,'ASPIRE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(203,13,'BELINA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(204,13,'CLUB WAGON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(205,13,'CONTOUR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(206,13,'CORCEL II');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(207,13,'COURIER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(208,13,'CROWN VICTORIA    ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(209,13,'DEL REY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(210,13,'ECOSPORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(211,13,'EDGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(212,13,'ESCORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(213,13,'EXPEDITION');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(214,13,'EXPLORER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(215,13,'F-100');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(216,13,'F-1000');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(217,13,'F-150');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(218,13,'F-250');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(219,13,'FIESTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(220,13,'FOCUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(221,13,'FURGLAINE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(222,13,'FUSION');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(223,13,'IBIZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(224,13,'KA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(225,13,'MONDEO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(226,13,'MUSTANG');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(227,13,'PAMPA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(228,13,'PROBE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(229,13,'RANGER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(230,13,'VERSAILLES ROYALE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(231,13,'TAURUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(232,13,'THUNDERBIRD');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(233,13,'TRANSIT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(234,13,'VERONA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(235,13,'VERSAILLES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(236,13,'WINDSTAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(238,1,'A-10');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(239,1,'A-20');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(240,1,'AGILE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(241,1,'ASTRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(242,1,'BLAZER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(243,1,'BONANZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(245,1,'C-10');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(246,1,'C-20');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(247,1,'CALIBRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(248,1,'CAMARO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(249,1,'CAPRICE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(250,1,'CAPTIVA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(251,1,'CARAVAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(252,1,'CAVALIER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(253,1,'CELTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(255,1,'CHEVY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(256,1,'CHEYNNE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(258,1,'COBALT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(259,1,'CORSA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(262,1,'CORVETTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(263,1,'CRUZE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(264,1,'D-10');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(265,1,'D-20');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(266,1,'IPANEMA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(267,1,'KADETT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(268,1,'LUMINA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(269,1,'MALIBU');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(271,1,'MERIVA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(272,1,'MONTANA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(274,1,'OMEGA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(275,1,'OPALA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(276,1,'PRISMA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(277,1,'S10');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(280,1,'SILVERADO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(281,1,'SONIC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(282,1,'SONOMA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(283,1,'SPACEVAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(284,1,'SS10');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(285,1,'SUBURBAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(287,1,'SYCLONE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(288,1,'TIGRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(289,1,'TRACKER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(290,1,'TRAFIC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(291,1,'VECTRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(292,1,'VERANEIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(293,1,'ZAFIRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(294,75,'HOVER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(295,17,'BR-800');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(296,17,'CARAJAS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(297,17,'TOCANTINS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(298,17,'XAVANTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(299,17,'VIP');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(300,76,'TOWNER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(301,7,'ACCORD');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(302,7,'CITY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(303,7,'CIVIC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(304,7,'CR-V');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(305,7,'FIT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(306,7,'ODYSSEY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(307,7,'PASSPORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(308,7,'PRELUDE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(309,14,'ACCENT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(310,14,'ATOS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(311,14,'AZERA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(312,14,'COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(314,14,'ELANTRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(315,14,'EXCEL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(316,14,'GALLOPER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(317,14,'GENESIS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(318,14,'H1');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(319,14,'H100');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(321,14,'I30');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(323,14,'IX35');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(324,14,'MATRIX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(325,14,'PORTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(326,14,'SANTA FE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(327,14,'SCOUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(328,14,'SONATA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(329,14,'TERRACAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(330,14,'TRAJET');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(331,14,'TUCSON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(332,14,'VELOSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(333,14,'VERACRUZ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(334,84,'AMIGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(335,84,'HOMBRE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(336,84,'RODEO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(337,15,'J3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(338,15,'J5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(339,15,'J6');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(340,86,'DAIMLER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(341,86,'S-TYPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(342,86,'X-TYPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(345,86,'MODELOS XJ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(352,86,'MODELOS XK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(354,87,'CHEROKEE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(355,87,'COMMANDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(356,87,'COMPASS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(357,87,'GRAND CHEROKEE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(358,87,'WRANGLER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(359,88,'TOPIC VAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(360,89,'JIPE MONTEZ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(361,89,'PICAPE MONTEZ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(362,16,'BESTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(363,16,'BONGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(364,16,'CADENZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(365,16,'CARENS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(366,16,'CARNIVAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(367,16,'CERATO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(368,16,'CERES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(369,16,'CLARUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(370,16,'MAGENTIS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(371,16,'MOHAVE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(372,16,'OPIRUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(373,16,'OPTIMA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(374,16,'PICANTO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(375,16,'SEPHIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(376,16,'SHUMA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(377,16,'SORENTO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(378,16,'SOUL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(379,16,'SPORTAGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(380,94,'LAIKA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(381,94,'NIVA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(382,94,'SAMARA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(383,12,'GALLARDO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(384,12,'MURCIELAGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(385,96,'DEFENDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(386,96,'DISCOVERY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(389,96,'FREELANDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(391,96,'NEW RANGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(392,96,'RANGE ROVER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(393,97,'ES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(396,97,'GS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(397,97,'IS-300');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(398,97,'LS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(400,97,'RX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(402,97,'SC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(403,98,'320');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(404,98,'620');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(405,100,'H1');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(406,101,'ELAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(407,101,'ESPRIT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(408,102,'SCORPIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(409,104,'222');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(410,104,'228');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(411,104,'3200');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(412,104,'430');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(413,104,'COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(414,104,'GHIBLI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(415,104,'GRANCABRIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(416,104,'GRANSPORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(417,104,'GRANTURISMO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(418,104,'QUATTROPORTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(419,104,'SHAMAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(420,104,'SPIDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(422,106,'PICK-UP');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(423,108,'323');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(424,108,'626');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(425,108,'929');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(426,108,'B-2500');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(427,108,'B2200');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(428,108,'MILLENIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(429,108,'MPV');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(430,108,'MX-3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(431,108,'MX-5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(432,108,'NAVAJO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(433,108,'PROTEGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(434,108,'RX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(467,4,'CLASSE A');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(468,4,'CLASSE B');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(469,4,'CLASSE R');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(498,4,'CLASSE GLK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(531,4,'SPRINTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(532,110,'MYSTIQUE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(533,110,'SABLE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(534,112,'550');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(535,112,'MG6');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(536,113,'COOPER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(537,113,'ONE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(538,111,'3000');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(539,111,'AIRTREK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(540,111,'ASX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(541,111,'COLT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(542,111,'DIAMANT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(543,111,'ECLIPSE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(544,111,'EXPO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(545,111,'GALANT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(546,111,'GRANDIS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(547,111,'L200');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(548,111,'L300');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(549,111,'LANCER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(550,111,'MIRAGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(551,111,'MONTERO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(552,111,'OUTLANDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(553,111,'PAJERO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(554,111,'SPACE WAGON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(555,114,'BG-TRUCK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(556,43,'350Z');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(557,43,'ALTIMA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(558,43,'AX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(559,43,'D-21');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(560,43,'FRONTIER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(562,43,'KING-CAB');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(563,43,'LIVINA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(564,43,'MARCH');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(565,43,'MAXIMA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(567,43,'MURANO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(568,43,'NX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(569,43,'PATHFINDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(571,43,'PRIMERA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(572,43,'QUEST');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(573,43,'SENTRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(574,43,'STANZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(575,43,'180SX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(576,43,'TERRANO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(577,43,'TIIDA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(578,43,'VERSA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(579,43,'X-TRAIL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(580,43,'XTERRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(581,43,'ZX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(582,22,'106');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(583,22,'205');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(584,22,'206');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(585,22,'207');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(586,22,'3008');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(587,22,'306');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(588,22,'307');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(589,22,'308');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(590,22,'405');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(591,22,'406');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(592,22,'407');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(593,22,'408');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(594,22,'504');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(595,22,'505');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(596,22,'508');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(597,22,'605');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(598,22,'607');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(599,22,'806');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(600,22,'807');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(601,22,'BOXER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(602,22,'HOGGAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(603,22,'PARTNER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(604,22,'RCZ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(605,123,'GRAN VOYAGER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(606,123,'SUNDANCE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(607,69,'TRANS-AM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(608,69,'TRANS-SPORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(609,70,'911');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(612,70,'BOXSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(613,70,'CAYENNE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(614,70,'CAYMAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(615,70,'PANAMERA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(617,24,'21 SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(618,24,'CLIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(619,24,'DUSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(620,24,'EXPRESS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(621,24,'FLUENCE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(622,24,'KANGOO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(623,24,'LAGUNA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(624,24,'LOGAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(625,24,'MASTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(626,24,'MEGANE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(627,24,'SAFRANE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(628,24,'SANDERO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(629,24,'SCENIC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(630,24,'SYMBOL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(631,24,'TRAFIC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(632,24,'TWINGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(634,137,'9000');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(635,162,'SL-2');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(636,130,'CORDOBA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(637,130,'IBIZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(638,130,'INCA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(641,142,'FORTWO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(642,21,'ACTYON SPORTS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(643,21,'CHAIRMAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(644,21,'ISTANA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(645,21,'KORANDO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(646,21,'KYRON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(647,21,'MUSSO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(648,21,'REXTON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(649,8,'FORESTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(650,8,'IMPREZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(651,8,'LEGACY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(652,8,'OUTBACK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(653,8,'SVX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(654,8,'TRIBECA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(655,8,'VIVIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(656,59,'BALENO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(657,59,'GRAND VITARA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(658,59,'IGNIS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(660,59,'JIMNY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(662,59,'SUPER CARRY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(663,59,'SWIFT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(664,59,'SX4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(665,59,'VITARA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(666,59,'WAGON R');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(667,146,'STARK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(668,23,'AVALON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(669,23,'BANDEIRANTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(670,23,'CAMRY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(671,23,'CELICA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(672,23,'COROLLA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(673,23,'CORONA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(674,23,'HILUX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(675,23,'LAND CRUISER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(676,23,'MR-2');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(677,23,'PASEO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(678,23,'PREVIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(679,23,'RAV4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(680,23,'SUPRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(682,149,'PANTANAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(684,149,'T-4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(685,53,'400 SERIES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(687,53,'850');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(688,53,'900 SERIES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(700,2,'AMAROK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(701,2,'APOLLO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(702,2,'BORA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(703,2,'CARAVELLE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(704,2,'CORRADO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(706,2,'EOS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(707,2,'EUROVAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(708,2,'FOX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(709,2,'FUSCA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(710,2,'GOL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(711,2,'GOLF');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(713,2,'JETTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(714,2,'KOMBI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(715,2,'LOGUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(717,2,'PARATI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(718,2,'PASSAT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(719,2,'POINTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(720,2,'POLO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(722,2,'SANTANA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(723,2,'SAVEIRO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(725,2,'SPACEFOX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(726,2,'TIGUAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(727,2,'TOUAREG');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(729,2,'VOYAGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(732,25,'ZDX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(737,3,'140');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(755,2,'BRASILIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(756,13,'BRASILVAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(775,13,'CORCEL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(803,3,'PALIO WEEKEND');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(806,13,'FOCUS SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(807,13,'FIESTA SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(808,13,'FIESTA TRAIL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(810,22,'207 SW');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(811,13,'ESCORT SW');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(812,22,'307 SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(813,22,'307 SW');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(815,5,'C4 PALLAS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(816,5,'C4 PICASSO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(817,5,'C4 VTR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(818,24,'CLIO SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(819,23,'COROLLA FIELDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(824,23,'HILUX SW4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(825,24,'MEGANE GRAND TOUR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(827,24,'SANDERO STEPWAY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(829,5,'XSARA PICASSO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1360,131,'COLHEITADEIRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1361,158,'PICKUP F75');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1362,17,'X12');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1365,1,'BEL AIR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1366,36,'RX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1369,1,'C-14');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1370,155,'SRX4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1372,1,'C-15');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1373,1,'BRASIL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1377,18,'POLARA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1380,3,'600');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1382,13,'F-01');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1383,13,'FALCON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1384,13,'GALAXIE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1386,13,'MAVERICK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1387,13,'MODELO A');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1388,13,'NEW FIESTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1389,82,'LINHA FX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1391,124,'GTS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1392,80,'H3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1394,14,'PRIME');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1395,14,'TIBURON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1397,87,'JEEP');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1398,87,'CJ5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1399,239,'TC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1404,4,'CLASSE CLC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1405,4,'CLASSE CLS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1408,110,'MONTEREY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1411,114,'TOPSPORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1412,114,'TARGA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1414,114,'X8');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1415,43,'370Z');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1418,124,'GTB');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1419,124,'GTC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1420,124,'GTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1421,115,'AUSTIN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1423,24,'7TL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1424,24,'19');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1426,175,'CONVERSÍVEL ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1427,17,'SUPERMINI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1428,2,'TL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1429,3,'TOPOLINO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1430,23,'SR5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1431,23,'VITZ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1432,2,'VARIANT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1454,57,'CANDANGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1460,2,'SP2');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1466,258,'RECORB');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1467,2,'POLAUTO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1508,24,'GORDINI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1509,265,'MINX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1971,23,'ETIOS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1972,1,'ONIX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1973,14,'HB20');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1975,36,'330');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1976,36,'520');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1978,36,'730');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1980,36,'M1');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1982,36,'SERIE Z');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1983,4,'CLASSE SLK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1984,4,'CLASSE C');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1985,4,'CLASSE E');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1986,4,'CLASSE CL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1987,4,'CLASSE CLK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1988,4,'CLASSE S');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1989,4,'CLASSE SL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1990,4,'CLASSE SLS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1991,4,'CLASSE G');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1992,4,'CLASSE GL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(1993,4,'CLASSE M');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2032,288,'1500');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2061,14,'EQUUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2067,12,'350 GT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2068,12,'400 GT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2069,12,'MIURA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2070,12,'ISLERO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2071,12,'ESPADA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2072,12,'COUNTACH');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2073,12,'DIABLO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2074,12,'ZAGATO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2075,12,'ALAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2076,12,'LM002');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2077,12,'REVENTON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2078,12,'ANKONIAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2080,12,'AVENTADOR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2081,12,'SESTO ELEMENTO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2082,15,'J3 TURIN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2083,15,'J2');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2084,24,'SANDERO GT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2087,1,'SPIN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2088,1,'TRAILBLAZER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2097,5,'C3 PICASSO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2098,5,'GRAND C4 PICASSO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2099,5,'JUMPER MINIBUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2100,5,'JUMPER VETRATO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2101,22,'207 SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2102,22,'207 QUIKSILVER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2103,22,'207 ESCAPADE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2104,22,'308 CC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2105,22,'BOXER PASSAGEIRO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2106,13,'NEW FIESTA SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2108,13,'TRANSIT PASSAGEIRO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2109,13,'TRANSIT CHASSI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2110,32,'A4 AVANT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2111,32,'S4 AVANT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2112,32,'A5 SPORTBACK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2113,32,'A5 CABRIOLET');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2114,32,'S5 COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2115,32,'S5 SPORTBACK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2116,32,'S5 CABRIOLET');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2117,32,'A6 AVANT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2118,32,'A6 ALLROAD');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2119,32,'S6 AVANT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2120,32,'S7');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2121,32,'TT ROADSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2122,32,'TT RS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2123,32,'TT RS ROADSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2124,32,'TTS ROADSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2125,32,'R8 SPYDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2126,32,'R8 GT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2127,32,'R8 GT SPYDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2129,10,'F12');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2130,10,'458 SPIDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2131,10,'458 ITALIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2132,10,'FF');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2133,10,'599');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2134,10,'SA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2135,10,'CHALLENGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2136,10,'SUPERAMERICA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2137,10,'F430 SPIDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2138,10,'430');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2139,10,'612 SESSANTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2140,10,'599 GTB');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2141,10,'SCUDERIA SPIDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2142,10,'512');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2143,10,'456 GT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2144,10,'348 GTS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2145,10,'348 SPIDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2146,10,'F355');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2147,10,'F355 SPIDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2148,10,'F50');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2149,10,'355 SPIDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2150,10,'360 MODENA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2151,111,'PAJERO FULL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2152,111,'PAJERO DAKAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2153,111,'PAJERO TR4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2154,111,'LANCER SPORTBACK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2155,111,'LANCER EVOLUTION');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2156,111,'L200 TRITON SAVANA    ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2157,111,'L200 TRITON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2159,43,'LIVINA X-GEAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2160,43,'GRAND LIVINA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2161,21,'NEW ACTYON SPORTS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2162,23,'PRIUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2163,114,'SPORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2164,114,'MTS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2165,114,'SPIDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2166,114,'KABRIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2167,114,'SAGA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2168,114,'SAGA II');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2169,114,'787');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2170,114,'X11');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2171,295,'GAIOLA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2175,18,'NITRO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2176,18,'CHALLENGER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2177,18,'DART');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2178,18,'LE BARON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2179,18,'CORDOBA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2180,18,'CHARGER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2181,19,'WINDSOR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2183,19,'CROSSFIRE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2184,19,'CORDOBA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2185,155,'ESCALADE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2186,41,'RIVIERA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2187,41,'COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2188,41,'CENTURY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2189,41,'APOLLO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2190,41,'CENTURION');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2191,41,'EIGHT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2192,41,'ELECTRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2193,41,'ESTATE WAGON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2194,41,'GRAN SPORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2195,41,'GSX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2196,41,'INVICTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2197,41,'LESABRE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2198,41,'LIMITED');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2199,41,'PARK AVENUE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2200,41,'RAINIER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2201,41,'REATTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2202,41,'REGAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2203,41,'RENDEZVOUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2204,41,'ROADMASTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2205,41,'ROYAUM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2206,41,'SKYHAWK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2207,41,'SKYLARK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2208,41,'SOMERSET');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2209,41,'SPECIAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2210,41,'SPORT WAGON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2211,41,'SUPER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2212,41,'TERRAZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2213,41,'WILDCAT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2214,41,'LACROSSE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2215,41,'ENCLAVE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2217,41,'GL8');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2218,41,'HRV');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2219,41,'LUCERNE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2230,13,'SIERRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2231,51,'BROUGHAM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2232,51,'CHAIRMAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2233,51,'DAMAS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2234,51,'GENTRA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2235,51,'MAEPSY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2236,51,'ISTANA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2237,51,'KALOS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2238,51,'KORANDO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2239,51,'LACETTI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2240,51,'LEMANS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2242,51,'MATIZ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2243,51,'MUSSO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2244,51,'NEXIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2245,51,'REZZO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2246,51,'ROYALE PRINCE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2247,51,'ROYALE SALON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2248,51,'STATESMAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2249,51,'TOSCA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2250,51,'WINSTORM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2252,158,'RURAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2253,18,'D100');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2259,4,'170');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2261,18,'CUSTOM ROYAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2262,1,'CLUB COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2263,18,'MAGNUM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2264,1,'GMC 100');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2265,69,'SOLSTICE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2266,158,'ITAMARATY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2267,86,'MARK V');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2268,124,'GT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2269,145,'CHAMPION');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2270,3,'BALILLA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2271,158,'INTERLAGOS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2272,17,'X15');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2273,13,'F-85');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2274,70,'SPEEDSTER 356');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2275,88,'TOPIC FURGAO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2276,88,'TOPIC ESCOLAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2279,4,'300D');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2280,4,'CLASSE TE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2283,23,'T-100');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2294,24,'MEGANE SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2295,32,'A4 CABRIOLET');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2298,82,'LINHA G');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2299,82,'LINHA G COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2300,82,'LINHA G CONVERSIVEL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2301,82,'LINHA M');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2302,82,'LINHA EX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2303,82,'LINHA JX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2304,82,'LINHA QX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2305,86,'MODELOS XF');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2306,86,'F-TYPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2307,86,'MARK VII');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2308,86,'MARK VIII');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2309,86,'MARK IX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2310,86,'MARK X');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2311,86,'E-TYPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2312,86,'C-TYPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2313,86,'D-TYPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2314,86,'MARK I');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2315,86,'MARK II');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2346,124,'GT4R');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2347,124,'SPYDER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2348,124,'GTI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2349,124,'AM1');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2350,124,'AM2');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2351,124,'AM3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2352,124,'AM4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2353,124,'AMV');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2377,7,'ACTY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2378,7,'AIRWAVE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2379,7,'ASCOT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2380,7,'BALLADE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2381,7,'BEAT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2382,7,'CR-X');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2383,7,'CONCERTO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2384,7,'CR-Z');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2385,7,'DOMANI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2386,7,'EDIX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2387,7,'ELEMENT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2388,7,'EV PLUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2389,7,'FCX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2390,7,'FR-V');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2392,7,'HR-V');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2393,7,'HSC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2394,7,'INSIGHT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2396,25,'TL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2397,7,'LIFE DUNK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2398,7,'LOGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2399,7,'MOBILIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2400,25,'MDX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2401,7,'ORTHIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2402,7,'PARTNER VAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2403,7,'PILOT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2404,7,'RIDGELINE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2405,7,'S2000');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2406,7,'S600');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2407,7,'S500');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2408,7,'S800');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2409,7,'STEPWGN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2410,7,'STREAM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2411,7,'THATS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2412,7,'VAMOZ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2413,7,'Z');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2414,7,'ZEST');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2441,59,'AERIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2442,59,'ALTO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2443,59,'APV');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2444,59,'KEI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2445,59,'LAPIN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2446,59,'MR WAGON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2447,59,'XL-7');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2448,59,'VERONA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2477,158,'JEEP CJ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2479,22,'306 CABRIOLET');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2484,57,'BELCAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2485,90,'M715');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2492,22,'407 SW');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2493,22,'307 CC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2499,1,'STYLELINE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2500,13,'ANGLIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2508,26,'GT2');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2509,1,'YUKON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2510,54,'SPORTSMAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2514,24,'21 NEVADA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2515,11,'VEYRON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2516,10,'ENZO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2517,22,'306 SW');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2528,28,'TI 80');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2532,70,'SPYDER 550');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2533,10,'380 GTB');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2534,149,'T-5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2536,18,'KINGSWAY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2537,1,'SSR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2540,1,'IMPALA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2541,22,'208');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2542,1,'GRAND BLAZER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2555,53,'100 SERIES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2558,53,'200 SERIES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2559,53,'300 SERIES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2561,53,'66');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2562,53,'700 SERIES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2563,53,'AMAZON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2564,53,'C303');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2566,53,'DUETT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2567,53,'L3314');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2568,53,'OV 4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2569,53,'P1800');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2570,53,'SUGGA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2571,13,'TT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2572,5,'ONCE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2573,13,'DE LUXE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2574,13,'CUSTOM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2575,13,'T-BUCKET');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2576,17,'G15');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2588,111,'PAJERO FULL 3D');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2589,111,'PAJERO SPORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2590,36,'120 CABRIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2591,36,'320 TOURING');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2592,36,'330 CABRIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2593,36,'SERIE 5 TOURING');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2594,36,'SERIE 6 CABRIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2595,36,'SERIE M CONVERSIVEL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2596,36,'M5 TOURING');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2597,36,'SERIE Z ROADSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2599,13,'KA SPORT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2600,2,'CC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2605,16,'CERATO KOUP');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2607,1,'ASTRO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2608,23,'COROLLA XRS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2609,23,'ETIOS SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2611,13,'FREESTYLE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2612,110,'COUGAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2615,102,'XUV 500');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2618,102,'XYLO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2619,102,'BOLERO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2620,102,'THAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2621,102,'AXE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2622,102,'LEGEND');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2623,87,'CJ3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2624,102,'ARMADA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2625,102,'CHASSI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2626,102,'SCORPIO PICK-UP');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2627,6,'STAR TRUCK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2628,6,'STAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2629,6,'STAR VAN CARGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2630,6,'STAR VAN PASSAGEIROS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2632,141,'ALVORADA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2633,141,'CHAMBORD');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2637,141,'PROFISSIONAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2639,141,'VEDETTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2640,141,'ARONDE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2641,141,'1200S');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2642,141,'1000');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2645,14,'HB20X');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2646,14,'HB20S');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2648,1,'MONZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2649,1,'CHEVETTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2650,98,'X60');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2651,1,'TRAX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2652,36,'118');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2653,36,'120');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2654,36,'130');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2655,36,'BAVARIA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2656,36,'C-2800');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2657,36,'318');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2658,36,'320');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2659,36,'318 CABRIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2660,36,'325 CABRIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2661,36,'530');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2662,36,'540');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2663,36,'550');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2664,36,'740');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2665,36,'750');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2666,36,'760');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2675,341,'MATRIX 4X4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2694,132,'A7');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2695,132,'A9');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2696,132,'A9 CARGO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2697,132,'T20');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2698,132,'T20 BAU');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2699,132,'T22');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2704,64,'SUPER 90 COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2705,17,'X20');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2706,17,'ITAIPU');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2707,17,'G800');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2708,17,'XEF');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2709,17,'MOTOMACHINE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2710,17,'BUGATO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2711,17,'QT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2716,57,'CAICARA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2717,57,'CARCARA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2718,57,'FISSORE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2719,57,'MALZONI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2720,57,'VEMAGUET');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2727,5,'C4 LOUNGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2728,108,'CX-7');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2729,147,'TR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2730,147,'LUCENA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2731,147,'SEVETSE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2732,147,'RAGGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2733,53,'C70');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2734,53,'C30');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2735,53,'544');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2736,53,'S40');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2737,53,'S60');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2738,53,'S70');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2739,53,'S80');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2740,53,'V40');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2741,53,'V50');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2742,53,'V60');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2743,53,'V70');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2744,53,'S90');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2745,53,'XC60');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2746,53,'XC70');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2747,53,'XC90');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2748,53,'P1900');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2749,53,'PV36');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2750,53,'PV444');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2751,53,'PV544');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2752,53,'PV51');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2753,53,'PV654');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2754,53,'C50');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2755,4,'190');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2756,4,'CLASSE CLA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2757,4,'CLASSE V');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2758,4,'VANEO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2759,4,'CITAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2760,4,'VARIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2761,4,'CLASSE S CLASSICO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2809,15,'J3S');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2810,345,'PICK-UP');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2811,345,'VAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2823,5,'C3 SOLARIS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2824,5,'C3 XTR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2825,5,'C4 SOLARIS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2826,5,'C5 BREAK/TOURER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2827,5,'XSARA BREAK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2828,5,'XSARA VTS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2829,5,'XANTIA BREAK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2830,5,'XM BREAK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2831,5,'C15');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2832,5,'NEMO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2833,5,'VISA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2834,5,'C1');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2835,5,'C2');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2836,5,'C3 PLURIEL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2837,5,'DS4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2838,5,'DS5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2839,5,'JUMPY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2840,5,'C-CROSSER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2841,5,'C35');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2842,5,'C25');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2843,5,'CX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2844,5,'CX BREAK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2845,5,'AXEL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2846,5,'DYANE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2847,5,'GS/GSA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2848,5,'GS/GSA BREAK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2849,5,'MEHARI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2850,5,'SAXO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2851,5,'SM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2852,5,'ELYSEE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2853,24,'MASTER MINIBUS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2854,47,'CELER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2855,47,'CELER SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2856,47,'CIELO SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2857,32,'A1 SPORTBACK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2858,32,'A1 QUATTRO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2859,32,'A3 SPORTBACK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2860,32,'RS4 AVANT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2861,32,'A8L W12');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2862,32,'R8 V10');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2863,13,'RANGER CD');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2864,15,'T140');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2865,36,'X1');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2866,36,'X3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2867,36,'X5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2868,36,'X6');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2869,36,'840');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2870,36,'850');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2871,36,'645');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2872,36,'650');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2874,7,'FIT TWIST');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2876,346,'MP4');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2877,346,'F1');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2878,13,'MONDEO SW');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2879,13,'ESCORT SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2880,13,'ESCORT CONVERSIVEL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2881,108,'MX-6');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2884,1,'CORISCO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2885,1,'CHEVELLE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2886,13,'EXCURSION');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2887,2,'TOURAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2890,13,'F-10000');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2891,22,'HOGGAR ESCAPADE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2901,13,'PHAETON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2913,2,'TRANSPORTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2914,16,'GRAND BESTA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2915,43,'200SX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2916,43,'240SX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2921,19,'300M');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2922,19,'300C TOURING');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2928,13,'TORINO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2931,1,'VENTURE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2932,1,'FLEETLINE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2933,1,'FLEETMASTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2934,1,'DELUXE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2936,13,'ESCORT XR3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2937,1,'MASTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2938,120,'TORONADO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2939,120,'SIX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2940,120,'EIGHT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2941,120,'DELUXE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2942,120,'SERIES 60');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2943,120,'SERIES 70');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2944,120,'SERIES 80');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2945,120,'SERIES 90');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2946,120,'STARFIRE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2947,120,'442');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2948,120,'CUTLASS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2949,120,'CUTLASS SUPREME');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2950,120,'CUTLASS SALON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2951,120,'CUTLASS CALAIS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2952,120,'CUTLASS CIERA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2953,120,'CUSTOM CRUISER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2954,120,'VISTA CRUISER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2955,120,'F-85');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2957,120,'FIRENZA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2958,120,'ACHIEVA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2959,120,'ALERO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2960,120,'AURORA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2961,120,'BRAVADA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2962,120,'INTRIGUE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2963,120,'SILHOUETTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2972,123,'SUPERBIRD');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2973,123,'FURY');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2974,123,'SPECIAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2975,123,'PROWLER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2976,123,'TRAIL DUSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2977,123,'VOYAGER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2978,123,'SCAMP');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2979,123,'ARROW');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2980,123,'PT50');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2981,123,'PT57');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2982,123,'PT81');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2983,123,'PT105');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2984,123,'PT125');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2985,123,'EXPRESS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2986,123,'VOYAGER EXPRESSO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2987,123,'NEON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2988,123,'LASER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2989,123,'CARAVELLE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2990,123,'STATION WAGON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2991,123,'MODEL Q');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2992,123,'MODEL P6');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2993,31,'DB9 COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2994,31,'DB9 VOLANTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2995,31,'VIRAGE COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2996,31,'RAPIDE S');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2997,31,'V12 VANTAGE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2998,31,'V8 VANTAGE COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(2999,31,'V8 VANTAGE ROADSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3000,31,'V8 VANTAGE S COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3001,31,'V8 VANTAGE S ROADSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3002,31,'VANQUISH COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3003,31,'VANQUISH VOLANTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3004,31,'V12 ZAGATO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3005,31,'DB5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3007,31,'DBS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3008,31,'DBS VOLANTE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3009,31,'CYGNET');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3010,31,'ONE-77');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3011,31,'DBR9');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3013,36,'M3');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3014,36,'M5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3015,36,'M6');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3016,36,'X6 M');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3017,113,'CABRIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3018,113,'COUPE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3019,113,'ROADSTER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3020,113,'COUNTRYMAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3021,113,'PACEMAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3022,113,'JOHN COOPER WORKS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3023,122,'ZONDA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3024,8,'NEW XV');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3025,8,'IMPREZA WRX HATCH');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3026,8,'IMPREZA WRX STI HATCH');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3027,8,'IMPREZA WRX STI SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3028,8,'IMPREZA WRX SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3030,23,'ETIOS CROSS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3031,12,'HURACAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3032,2,'UP');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(3080,195,'EXPLORER');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4964,142,'FORTWO CABRIO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4969,26,'GT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4970,26,'GTL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4971,26,'GTM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4972,26,'C2');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4973,26,'CRX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4974,26,'AC 2000');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4975,99,'AVIATOR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4976,99,'BLACKWOOD');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4977,99,'CAPRI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4978,99,'CONTINENTAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4979,99,'LS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4980,99,'MARK');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4981,99,'MARK LT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4982,99,'MKR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4983,99,'MKS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4984,99,'MKX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4985,99,'MKZ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4986,99,'NAVIGATOR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4987,99,'PREMIERE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4988,99,'TOWN CAR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4989,99,'VERSAILLES');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4990,99,'ZEPHYR');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4991,1,'CLASSIC');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(4992,21,'ACTYON');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5003,1,'MARAJO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5004,1,'SUPREMA');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5005,2,'NEW BEETLE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5006,2,'QUANTUM');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5007,2,'CROSSFOX');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5008,3,'MILLE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5009,534,'GC2');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5010,534,'EC7');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5011,98,'530');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5012,3,'MOBI');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5013,3,'TORO');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5014,87,'RENEGADE');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5015,24,'DUSTER OROCH');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5016,24,'SANDERO RS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5017,14,'HB20R');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5018,14,'GRAND SANTA FE    ');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5019,2,'GOLF VARIANT');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5020,2,'SPACE CROSS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5021,22,'2008');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5022,16,'QUORIS');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5023,16,'GRAND CARNIVAL');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5024,15,'T8');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5025,15,'T6');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5026,15,'T5');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5027,13,'KA SEDAN');
insert into modelo (pk_modelo, cod_marca, nom_modelo)values(5028,13,'FOCUS FASTBACK');